version: "{build}"

clone_depth: 10

os: Visual Studio 2015

init:
  - git config --global core.autocrlf input

platform:
  - x64

install:
  - cmd: SET PATH=C:\Program Files (x86)\MSBuild\14.0\bin\;%PATH%
  - cmd: SET PATH=C:\python27;%PATH%
  - cmd: bash script/cibuild

branches:
  only:
    - master

# disable build and test phases
build: off
test: off
