sudo: false
language: node_js
matrix:
  include:
    - node_js: "4"
    - node_js: "5"
    # We run both lint and unit on Node 6
    - node_js: "6"
      env: TEST_SUITE=test
    - node_js: "7"
    # We run coverage on Node 8
    - node_js: "8"
      env: TEST_SUITE=coverage
env:
  - TEST_SUITE=unit
script: npm run-script $TEST_SUITE
after_success:
  - if [ $TEST_SUITE = coverage ]; then npm run coveralls; fi
